[workspace]
members = [
    "source-compiler",
    "lib-projstd",
    "lib-asttoir",
    "lib-wasmgen",
    "lib-ir",
    "lib-backend-wasm",
    "wasm-test-harness",
    "wasm-test-driver",
    "wasm-test-local",
]
default-members = [
    "source-compiler",
]

[profile.release]
lto = true
